import Link from 'next/link'
import { requireAdmin } from '@/lib/admin'
import { createClient } from '@/lib/supabase/server'

export default async function AdminTasksPage(){
  const {admin}=await requireAdmin(); const supabase=await createClient()
  const {data,error}=await supabase.from('tasks').select('id,name,category,reward,estimated_minutes,proof_required,deadline,status,updated_at').order('updated_at',{ascending:false}).limit(200)
  return <main className="page"><Link href="/admin">← Admin</Link><div className="head"><div><p className="eyebrow">TASKAURA ADMIN · TASKS</p><h1>Task Manager</h1><p className="muted">{admin.role} · Create, edit and control task availability.</p></div><Link className="new" href="/admin/tasks/new">+ Create Task</Link></div>{error?<div className="panel">Unable to load tasks.</div>:<div className="list">{data?.map((t:any)=><article className="card" key={t.id}><div><strong>{t.name}</strong><span>{t.category} · ₹{Number(t.reward).toFixed(2)} · {t.estimated_minutes?`${t.estimated_minutes} min`:'Time not set'}</span><small>Proof: {t.proof_required?'Required':'Optional'} {t.deadline?`· Deadline ${new Date(t.deadline).toLocaleString('en-IN')}`:''}</small></div><div className="side"><b className={`status s-${t.status}`}>{t.status}</b><Link href={`/admin/tasks/${t.id}/edit`}>Edit</Link></div></article>)}</div>}<style>{`.page{min-height:100vh;background:#07070a;color:#fff;padding:24px 16px 50px;max-width:1100px;margin:auto}.page>a:first-child{color:#aaa;text-decoration:none;font-size:13px}.head{display:flex;justify-content:space-between;align-items:end;gap:16px;margin-top:25px}.eyebrow{font-size:10px;letter-spacing:.2em;color:#888}.page h1{margin:5px 0;font-size:30px}.muted,small{color:#999;font-size:12px}.new,.side a{color:#fff;text-decoration:none;border:1px solid #30303a;background:#15151b;border-radius:11px;padding:10px 13px;font-size:12px}.list{display:grid;gap:10px;margin-top:24px}.card,.panel{background:#111117;border:1px solid #292933;border-radius:16px;padding:16px;display:flex;justify-content:space-between;gap:16px}.card strong{display:block}.card span,.card small{display:block;margin-top:5px}.side{display:flex;align-items:center;gap:10px}.status{text-transform:capitalize;font-size:11px;color:#bbb}.s-active{color:#86efac}.s-paused,.s-draft{color:#fcd34d}.s-expired,.s-archived{color:#fca5a5}@media(max-width:600px){.head{align-items:stretch;flex-direction:column}.card{align-items:flex-start}.side{flex-direction:column;align-items:flex-end}}`}</style></main>
}
